try {
    throw new Error('There is an error!');
} catch (e) {
    console.log(e);
}
  